name: deployment workflow
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get the codes
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

      - name: build the project
        run: npm run build

      - name: create .env
        run: |
          touch .env
          echo "${{secrets.SERVER_ENV_FILE}}" > .env 
      - name: view .env
        run: cat .env

      - name: produce artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: build
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: download the artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
