name: deployment workflow
on:
  push:
    branches: main
jobs:
  build:
    runs-on: self-hosted
    steps: 
        - name: get the codes
          uses: actions/checkout@v4
        - name: install dependencies
          run: npm install
        - name: build the project
          run: npm run build
        - name: create .env
          run: |
            touch .env
            echo "${{secrets.SERVER_ENV_FILE}}" > .env
