name: deployment workflow
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get the codes
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

      - name: create .env
        run: |
          touch .env
          echo "process.env.REACT_APP_BACKEND_URL=${{secrets.REACT_APP_BACKEND_URL}}" | > .env 
          
      - name: view .env
        run: cat .env
      - name: produce artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: build
  # deploy:
  #   runs-on: self-hosted
  #   needs: build
  #   steps:
  #     - name: download the artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: dist-files
  #     - name: build the project
  #       run: npm run build
  
