name: deployment workflow
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get the codes
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

      - name: create .env
        run: |
          touch .env
          echo "REACT_APP_BACKEND_DEV=ec2-16-171-166-236.eu-north-1.compute.amazonaws.com:4000/api" | > .env 
          echo "REACT_APP_BACKEND_PROD=ec2-16-171-166-236.eu-north-1.compute.amazonaws.com:4000/api" | >> .env
          
      - name: view .env
        run: cat .env

      - name: produce artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: build
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: download the artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
