name: deployment workflow
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get the codes
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

      - name: build the project
        run: npm run build
        working-directory: ./

      - name: create dist folder
        run: mkdir dist/

      - name: produce artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

